candidates/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

import candidates.views as views

from .feeds import RecentChangesFeed

urlpatterns = \
    patterns('',
        (r'^', include(settings.ELECTION_APP_FULLY_QUALIFIED + '.urls')),
    )

patterns_to_format = [
    {
        'pattern': r'^$',
        'view': views.AddressFinderView.as_view(),
        'name': 'lookup-address',
    },
    {
        'pattern': r'^posts$',
        'view': views.PostListView.as_view(),
        'name': 'posts',
    },
    {
        'pattern': r'^election/{election}/constituencies$',
        'view': views.ConstituencyListView.as_view(),
        'name': 'constituencies'
    },
    {
        'pattern': r'^election/{election}/constituencies/unlocked$',
        'view': views.ConstituenciesUnlockedListView.as_view(),
        'name': 'constituencies-unlocked'
    },
    {
        'pattern': r'^election/{election}/constituencies/declared$',
        'view': views.ConstituenciesDeclaredListView.as_view(),
        'name': 'constituencies-declared'
    },
    {
        'pattern': r'^election/{election}/post/{post}/record-winner$',
        'view': views.ConstituencyRecordWinnerView.as_view(),
        'name': 'record-winner'
    },
    {
        'pattern': r'^election/{election}/post/{post}/retract-winner$',
        'view': views.ConstituencyRetractWinnerView.as_view(),
        'name': 'retract-winner'
    },
    {
        'pattern': r'^election/{election}/post/invalidate$',
        'view': views.InvalidatePostView.as_view(),
        'name': 'post-cache-invalidate'
    },
    {
        'pattern': r'^election/{election}/post/{post}/(?P<ignored_slug>.*).csv$',
        'view': views.ConstituencyDetailCSVView.as_view(),
        'name': 'constituency_csv'
    },
    {
        'pattern': r'^election/{election}/post/{post}/(?P<ignored_slug>.*)$',
        'view': views.ConstituencyDetailView.as_view(),
        'name': 'constituency'
    },
    {
        'pattern': r'^election/{election}/post/lock$',
        'view': views.ConstituencyLockView.as_view(),
        'name': 'constituency-lock'
    },
    {
        'pattern': r'^election/{election}/candidacy$',
        'view': views.CandidacyView.as_view(),
        'name': 'candidacy-create'
    },
    {
        'pattern': r'^election/{election}/candidacy/delete$',
        'view': views.CandidacyDeleteView.as_view(),
        'name': 'candidacy-delete'
    },
    {
        'pattern': r'^election/{election}/person/create/$',
        'view': views.NewPersonView.as_view(),
        'name': 'person-create'
    },
    {
        'pattern': r'^person/(?P<person_id>\d+)/update$',
        'view': views.UpdatePersonView.as_view(),
        'name': 'person-update'
    },
    {
        'pattern': r'^update-disallowed$',
        'view': TemplateView.as_view(template_name="candidates/update-disallowed.html"),
        'name': 'update-disallowed'
    },
    {
        'pattern': r'^all-edits-disallowed$',
        'view': TemplateView.as_view(template_name="candidates/all-edits-disallowed.html"),
        'name': 'all-edits-disallowed'
    },
    {
        'pattern': r'^person/(?P<person_id>\d+)/revert$',
        'view': views.RevertPersonView.as_view(),
        'name': 'person-revert'
    },
    {
        'pattern': r'^person/(?P<person_id>\d+)/merge$',
        'view': views.MergePeopleView.as_view(),
        'name': 'person-merge'
    },
    {
        'pattern': r'^person/(?P<person_id>\d+)(?:/(?P<ignored_slug>.*))?$',
        'view': views.PersonView.as_view(),
        'name': 'person-view'
    },
    {
        'pattern': r'^areas/(?P<type_and_area_ids>.*?)(?:/(?P<ignored_slug>.*))?$',
        'view': views.AreasView.as_view(),
        'name': 'areas-view',
    },
    {
        'pattern': r'^areas-of-type/(?P<mapit_type>.*?)(?:/(?P<ignored_slug>.*))?$',
        'view': views.AreasOfTypeView.as_view(),
        'name': 'areas-of-type-view',
    },
    {
        'pattern': r'^election/{election}/party/(?P<organization_id>[a-z-]+(:[-\d]+)?)/(?P<ignored_slug>.*)$',
        'view': views.PartyDetailView.as_view(),
        'name': 'party'
    },
    {
        'pattern': r'^election/{election}/parties/?$',
        'view': views.PartyListView.as_view(),
        'name': 'party-list'
    },
    {
        'pattern': r'^recent-changes$',
        'view': views.RecentChangesView.as_view(),
        'name': 'recent-changes'
    },
    {
        'pattern': r'^leaderboard$',
        'view': views.LeaderboardView.as_view(),
        'name': 'leaderboard'
    },
    {
        'pattern': r'^leaderboard/contributions.csv',
        'view': views.UserContributions.as_view(),
        'name': 'user-contributions'
    },
    {
        'pattern': r'^feeds/changes.xml',
        'view': RecentChangesFeed(),
        'name': 'changes_feed'
    },
    {
        'pattern': r'^help/api',
        'view': views.HelpApiView.as_view(),
        'name': 'help-api'
    },
    {
        'pattern': r'^help/about',
        'view': views.HelpAboutView.as_view(),
        'name': 'help-about'
    },
    {
        'pattern': r'^help/privacy',
        'view': TemplateView.as_view(template_name="candidates/privacy.html"),
        'name': 'help-privacy'
    },
    {
        'pattern': r'^copyright-question',
        'view': views.AskForCopyrightAssigment.as_view(),
        'name': 'ask-for-copyright-assignment'
    },
    {
        'pattern': r'^person/invalidate$',
        'view': views.InvalidatePersonView.as_view(),
        'name': 'person-cache-invalidate'
    },
]

urlpatterns += [
    url(
        p['pattern'].format(
            election=settings.ELECTION_RE,
            post=r'(?P<post_id>[-\w]+)',
        ),
        p['view'],
        name=p['name'],
    )
    for p in patterns_to_format
]

urlpatterns += [
    url(r'^numbers/', include('cached_counts.urls')),
    url(r'^moderation/', include('moderation_queue.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

elections/ar_elections_2015/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        r'^$',
        views.ArgentineAddressFinder.as_view(),
        name='lookup-address',
    ),
    url(
        r'^help/reutiliza$',
        TemplateView.as_view(template_name='candidates/reuse.html'),
        name='help-reuse',
    ),
]

mysite/urls.py
import sys

from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    url(r'^', include('candidates.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^upload_document/', include('official_documents.urls')),
    url(r'^results/', include('results.urls')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

if settings.DEBUG or ('test' in sys.argv):
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.conf.urls import patterns, url

from .views import IncompleteFieldView, TaskHomeView

urlpatterns = patterns('',
    url(r'^$', TaskHomeView.as_view(), name='tasks_home'),
    url(
        r'(?P<field>[a-z_\-\.]+)/',
        IncompleteFieldView.as_view(),
        name='incomplete_view',
    ),
)

candidates/models/db.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db.models.signals import post_save
from django.utils.translation import ugettext as _


class MaxPopItIds(models.Model):
    popit_collection_name = models.CharField(max_length=255)
    max_id = models.IntegerField(default=0)

    @classmethod
    def get_max_persons_id(cls):
        try:
            return cls.objects.get(popit_collection_name="persons").max_id
        except ObjectDoesNotExist:
            persons_max = cls(popit_collection_name="persons")
            persons_max.save()
            return persons_max.max_id

    @classmethod
    def update_max_persons_id(cls, max_id):
        max_persons, created = cls.objects.get_or_create(
            popit_collection_name="persons")
        if max_id > max_persons.max_id:
            max_persons.max_id = max_id
            max_persons.save()
        else:
            raise ValueError(_('given max_id is lower than the previous one ({'
                             '0} vs {1})').format(max_id, max_persons.max_id))


class LoggedAction(models.Model):
    '''A model for logging the actions of users on the site

    We record the changes that have been made to a person in PopIt in
    that person's 'versions' field, but is not much help for queries
    like "what has John Q User been doing on the site?". The
    LoggedAction model makes that kind of query easy, however, and
    should be helpful in tracking down both bugs and the actions of
    malicious users.'''

    user = models.ForeignKey(User, blank=True, null=True)
    action_type = models.CharField(max_length=64)
    popit_person_new_version = models.CharField(max_length=32)
    popit_person_id = models.CharField(max_length=256)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    ip_address = models.CharField(max_length=50, blank=True, null=True)
    source = models.TextField()


class PersonRedirect(models.Model):
    '''This represents a redirection from one person ID to another

    This is typically used to redirect from the person that is deleted
    after two people are merged'''
    old_person_id = models.IntegerField()
    new_person_id = models.IntegerField()


class UserTermsAgreement(models.Model):
    user = models.OneToOneField(User, related_name='terms_agreement')
    assigned_to_dc = models.BooleanField(default=False)


def create_user_terms_agreement(sender, instance, created, **kwargs):
    if created:
        UserTermsAgreement.objects.create(user=instance)

post_save.connect(create_user_terms_agreement, sender=User)

candidates/views/agreement.py
from django.views.generic import FormView
from django.http import HttpResponseRedirect
from django.utils.http import urlquote
from urlparse import urlparse

from ..forms import UserTermsAgreementForm

class AskForCopyrightAssigment(FormView):

    form_class = UserTermsAgreementForm
    template_name = 'candidates/ask-for-copyright-assignment.html'

    def get_initial(self):
        initial = super(AskForCopyrightAssigment, self).get_initial().copy()
        next_url = self.request.GET['next']
        parsed_url = urlparse(next_url)
        initial['next_path'] = parsed_url.path
        return initial

    def form_valid(self, form):
        ta = self.request.user.terms_agreement
        ta.assigned_to_dc = True
        ta.save()
        return HttpResponseRedirect(form.cleaned_data['next_path'])

    def get_context_data(self, **kwargs):
        context = super(AskForCopyrightAssigment, self) \
            .get_context_data(**kwargs)
        context['next_path_escaped'] = urlquote(self.request.GET['next'])
        return context

candidates/views/areas.py
# -*- coding: utf-8 -*-

import re

from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseBadRequest
from django.views.generic import TemplateView
from django.utils.text import slugify
from django.utils.translation import ugettext as _

from candidates.cache import get_post_cached, UnknownPostException
from candidates.models.auth import get_edits_allowed
from candidates.popit import PopItApiMixin

from ..election_specific import AREA_POST_DATA, MAPIT_DATA
from ..forms import NewPersonForm
from .helpers import get_people_from_memberships

class AreasView(PopItApiMixin, TemplateView):
    template_name = 'candidates/areas.html'

    def get(self, request, *args, **kwargs):
        self.types_and_areas = []
        for type_and_area in kwargs['type_and_area_ids'].split(','):
            m = re.search(r'^([A-Z0-9]{3})-(\d+)$', type_and_area)
            if not m:
                message = _("Malformed type and area: '{0}'")
                return HttpResponseBadRequest(message.format(type_and_area))
            self.types_and_areas.append(m.groups())
        try:
            view = super(AreasView, self).get(request, *args, **kwargs)
        except UnknownPostException:
            message = _("Malformed type and area: '{0}'")
            return HttpResponseBadRequest(message.format(kwargs['type_and_area_ids']))
        return view

    def get_context_data(self, **kwargs):
        context = super(AreasView, self).get_context_data(**kwargs)
        all_area_names = set()
        context['posts'] = []
        for mapit_type, area_id in self.types_and_areas:
            # Show candidates from the current elections:
            for election, election_data in settings.ELECTIONS_CURRENT:
                mapit_generation = election_data['mapit_generation']
                if mapit_type in election_data['mapit_types']:
                    mapit_tuple = (mapit_type, mapit_generation)
                    post_id = AREA_POST_DATA.get_post_id(election, mapit_type, area_id)
                    post_data = get_post_cached(self.api, post_id)['result']
                    area_name = MAPIT_DATA.areas_by_id[mapit_tuple][area_id]['name']
                    all_area_names.add(area_name)
                    locked = post_data.get('candidates_locked', False)
                    current_candidates, _ = get_people_from_memberships(
                        election_data,
                        post_data['memberships'],
                    )
                    context['posts'].append({
                        'election': election,
                        'election_data': election_data,
                        'post_data': post_data,
                        'candidates_locked': locked,
                        'candidate_list_edits_allowed':
                        get_edits_allowed(self.request.user, locked),
                        'candidates': current_candidates,
                        'add_candidate_form': NewPersonForm(
                            election=election,
                            initial={
                                ('constituency_' + election): post_id,
                                ('standing_' + election): 'standing',
                            },
                            hidden_post_widget=True,
                        ),
                    })
        context['all_area_names'] = u' — '.join(all_area_names)
        context['suppress_official_documents'] = True
        return context

class AreasOfTypeView(PopItApiMixin, TemplateView):
    template_name = 'candidates/areas-of-type.html'

    def get_context_data(self, **kwargs):
        context = super(AreasOfTypeView, self).get_context_data(**kwargs)
        requested_mapit_type = kwargs['mapit_type']
        all_mapit_tuples = set(
            (mapit_type, election_data['mapit_generation'])
            for election, election_data in settings.ELECTIONS_CURRENT
            for mapit_type in election_data['mapit_types']
            if mapit_type == requested_mapit_type
        )
        if not all_mapit_tuples:
            raise Http404(_("Area '{0}' not found").format(requested_mapit_type))
        if len(all_mapit_tuples) > 1:
            message = _("Multiple MapIt generations for type {mapit_type} found")
            raise Exception(message.format(mapit_type=requested_mapit_type))
        mapit_tuple = list(all_mapit_tuples)[0]
        areas = [
            (
                reverse(
                    'areas-view',
                    kwargs={
                        'type_and_area_ids': '{type}-{area_id}'.format(
                            type=requested_mapit_type,
                            area_id=area['id']
                        ),
                        'ignored_slug': slugify(area['name'])
                    }
                ),
                area['name'],
                area['type_name'],
            )
            for area in MAPIT_DATA.areas_by_id[mapit_tuple].values()
        ]
        areas.sort(key=lambda a: a[1])
        context['areas'] = areas
        context['area_type_name'] = _('[No areas found]')
        if areas:
            context['area_type_name'] = areas[0][2]
        return context

candidates/views/help.py
from django.conf import settings
from django.views.generic import TemplateView

from ..popit import PopItApiMixin, get_base_url

class HelpApiView(PopItApiMixin, TemplateView):
    template_name = 'candidates/api.html'

    def get_context_data(self, **kwargs):
        context = super(HelpApiView, self).get_context_data(**kwargs)

        context['current_csv_list'] = []
        for election, election_data in settings.ELECTIONS_CURRENT:
            context['current_csv_list'].append({'slug': election, 'name': election_data['name']})

        context['historic_csv_list'] = []
        current_slugs = [election['slug'] for election in context['current_csv_list']]
        for election, election_data in settings.ELECTIONS_BY_DATE:
            if election not in current_slugs:
                context['historic_csv_list'].append(
                    {'slug': election, 'name': election_data['name']})

        context['popit_url'] = get_base_url()
        return context


class HelpAboutView(TemplateView):
    template_name = 'candidates/about.html'

candidates/templates/candidates/_photo-credit.html
{% load i18n %}
{% with contributor=image.uploaded_by_user %}
{% with user_reason=image.user_why_allowed %}
{% with mod_reason=image.moderator_why_allowed %}
{% with user_comment=image.user_justification_for_use %}

  {% if contributor %}
    {% blocktrans %}This photo was uploaded by the user ‘{{ contributor }}’.{% endblocktrans %}
  {% endif %}
  {% if user_reason and user_reason != 'other'  %}
    {% trans "Their justification for its use on the site was:" %}
    {% include 'candidates/_photo-expand-reason.html' with reason=user_reason %}.
  {% endif %}
  {% if user_comment %}
    {% blocktrans %}They commented: “{{ user_comment }}”.{% endblocktrans %}
  {% endif %}
  {% if mod_reason != user_reason %}
    {% blocktrans trimmed %}The volunteer moderator who reviewed this photo picked a
    different justification for its use on the site, which was:{% endblocktrans %}
    {% include 'candidates/_photo-expand-reason.html' with reason=mod_reason %}.
  {% endif %}

  {# Photos not uploaded from the review queue have different metadata: #}

  {% if 'Approved from photo moderation queue' not in image.notes %}
    {% if image.source %}
      {% blocktrans with source=image.source %}The source of the image was “{{ source }}”.{% endblocktrans %}
    {% endif %}
    {% if image.notes and 'md5sum:' not in image.notes %}
      {% blocktrans with notes=image.notes %}Notes about this image: “{{ notes }}”.{% endblocktrans %}
    {% endif %}
  {% endif %}

{% endwith %}
{% endwith %}
{% endwith %}
{% endwith %}

candidates/templates/candidates/_source-plain.html
{% load i18n %}
<form method="post" action="{% url action %}">
  {% csrf_token %}
  <input type="hidden" name="person_id" value="{{ person.id }}"/>
  <input type="hidden" name="post_id" value="{{ constituency.id }}"/>
  <label for="id_source">{% trans "Please indicate your source for that information in the box below:" %}</label>
  <div class="row">
    <div class="small-12 medium-8 large-9 columns">
      <input type="text" name="source" id="id_source" maxlength="512"/>
    </div>
    <div class="small-6 medium-4 large-3 columns">
      <input type="submit" class="button expand" value="{% trans "Save changes" %}">
    </div>
  </div>
</form>

candidates/templates/candidates/about.html
{% extends 'base.html' %}
{% load i18n %}

{% block body_class %}{% endblock %}

{% block title %}{% trans "About this site" %}{% endblock %}

{% block hero %}
  <h1>{% trans "About this site" %}</h1>
{% endblock %}

{% block content %}
{% with email=settings.SUPPORT_EMAIL %}

<div class="help-about">

<p>{% blocktrans trimmed %}
Please email <a href="mailto:{{ email }}">{{ email }}</a>
with any feedback or bug reports. If you'd like to discuss this
site or any other project relating to elections in the UK, we'd
suggest that you post to
the <a href="https://groups.google.com/forum/#!forum/democracy-club">Democracy
Club Google Group</a>.
{% endblocktrans %}</p>

<p>{% blocktrans trimmed %}
The source code for this site
is <a href="https://github.com/mysociety/yournextrepresentative/">available
on GitHub</a>, and you can find
a <a href="https://github.com/mysociety/yournextrepresentative/issues">list
of known bugs</a> there as well.
{% endblocktrans %}</p>

<p>{% blocktrans trimmed %}
This site was developed by Mark Longair (mySociety), Sym Roe
(Democracy Club) and Zarino Zappia (mySociety).
{% endblocktrans %}</p>

<p>{% blocktrans trimmed %}
The data on candidates from the last UK general election in
2010 is all taken from Edmund von der
Burg's <a href="http://www.yournextmp.com">YourNextMP.com</a>,
with many thanks.
{% endblocktrans %}</p>

{% url 'help-api' as api_url %}
<p>{% blocktrans trimmed %}
You can use the data from this site, via the
<a href="{{ api_url }}">API or CSV download</a>, under the
terms of the Creative Commons license
<a href="https://creativecommons.org/licenses/by-sa/4.0/">Attribution-ShareAlike
(CC-BY-SA)</a> with the exception of:
{% endblocktrans %}</p>

<ul>
    <li>{% trans "The party logos, which are taken from the Electoral Commission's website" %}</li>
    <li>{% blocktrans trimmed %}
Candidate photos, which are typically either submitted by the candidates
themselves, or from sources where it seems reasonable that we might use them on
this site, such as the party's official page for that candidate, or their
social media profile picture.
{% endblocktrans %}</li>
</ul>

<p>{% blocktrans trimmed %}
If the CC-BY-SA licence is problematic for you, but you feel that you have a
worthwhile use of the data in mind, please <a href="mailto:{{ email }}">contact
us</a> to discuss your situation further.
{% endblocktrans %}</p>

<p>{% blocktrans trimmed %}
For complicated reasons relating to database licensing, we have put
the data as of the 4th of March 2015 into the public domain by
declaring it to
be <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0</a>. This
data is available
<a href="{{ MEDIA_URL }}csv-archives/cc0-snapshot-out-of-date/">here</a>
but please be warned that this snapshot will become inaccurate very quickly
- please use
<a href="{{ api_url }}">the up-to-date data</a> instead.
{% endblocktrans %}

<h3>{% trans "Privacy Policy" %}</h3>

{% url 'help-privacy' as url %}
<p>{% blocktrans trimmed %}
The privacy policy of this site can be found
<a href="{{ url }}">here</a>.
{% endblocktrans %}</p>

<h3>{% trans "Disclaimer" %}</h3>

<p>{% blocktrans trimmed %}
The data on this website is crowd-sourced and may not be
complete (or may contain inaccuracies). If you find an error,
please either update the page yourself, or
<a href="mailto:{{ email }}">email us</a> to report
the problem.{% endblocktrans %}</p>

</div>

{% endwith %}
{% endblock %}

candidates/templates/candidates/all-edits-disallowed.html
{% extends 'base.html' %}
{% load i18n %}

{% block body_class %}{% endblock %}

{% block title %}{% trans "Update Disallowed" %}{% endblock %}

{% block hero %}
  <h1>{% trans "Update Disallowed" %}</h1>
{% endblock %}

{% block content %}

<h2>{% trans "Update Disallowed" %}</h2>

  {% include 'candidates/_edits_disallowed_message.html' %}

{% endblock %}

candidates/templates/candidates/areas-of-type.html
{% extends 'base.html' %}
{% load i18n %}

{% load metadescription %}
{% load standing %}
{% load exists %}

{% block body_class %}areas-of-type{% endblock %}

{% block title %}{% blocktrans %}{{ area_type_name }}{% endblocktrans %}{% endblock %}

{% block hero %}
  <h1>{% blocktrans %}{{ area_type_name }}{% endblocktrans %}</h1>
{% endblock %}

{% block content %}

  <ul>
    {% for area_url, area_name in areas %}
      <li><a href="{{ area_url }}">{{ area_name }}</a></li>
    {% endfor %}
  </ul>

{% endblock %}

candidates/templates/candidates/candidacy-delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block body_class %}candidacy-delete-demand-source{% endblock %}

{% block title %}{% blocktrans with name=person.name %}How do you know that {{ name }} isn’t standing?{% endblocktrans %}{% endblock %}

{% block hero %}
  <h1>{% blocktrans with name=person.name %}How do you know that {{ name }} isn’t standing?{% endblocktrans %}</h1>
{% endblock %}

{% block content %}

<p>{% blocktrans trimmed with name=person.name election_name=election_data.name %}
Before updating our records we need to know the source for
your information that {{ name }} <strong>isn’t</strong>
standing for election to the post of {{ post_label }} in the
{{ election_name }}.{% endblocktrans %}</p>

{% include 'candidates/_source-plain.html' with action='candidacy-delete' %}

{% endblock %}

candidates/templates/candidates/party-list.html
{% extends 'base.html' %}
{% load i18n %}

{% block body_class %}party-list{% endblock %}

{% block title %}{% trans "All parties eligible for the UK 2015 General Election" %}{% endblock %}

{% block hero %}
  <h1>{% trans "All Parties" %}</h1>
{% endblock %}

{% block content %}

<h2>{% blocktrans with election_name=election_data.name %}All parties with any candidates standing in {{ election_name }}{% endblocktrans %}</h2>

<ul class="party-list">
  {% for p in parties %}
    <li><a href="{% url 'party' election=election organization_id=p.1 ignored_slug=p.0|slugify %}">{{ p.0 }}</a></li>
  {% endfor %}
</ul>

{% endblock %}

candidates/templates/candidates/person-versions.html
{% load prettyjson %}
{% load i18n %}

<div class="person__versions">
    <h2>{% trans "All versions" %}</h2>
    {% for version in person.version_diffs %}
      <div class="version">
        <dl>
          <dt>{% trans "Version" %}</dt>
          <dd>
            {{ version.version_id }} <a class="button tiny js-toggle-full-version-json">{% trans "Hide full version" %}</a>
            <pre class="full-version-json">{{ version.data|prettyjson }}</pre>
          </dd>
          <dt>{% trans "Username" %}</dt>
          <dd>{{ version.username }}</dd>
          <dt>{% trans "Timestamp" %}</dt>
          <dd>{{ version.timestamp }}</dd>
          <dt>{% trans "Source" %}</dt>
          <dd>{{ version.information_source }}</dd>
          <dt>{% trans "Changes made" %}</dt>
          <dd>
            <p class="version-diff">
              {% for operation in version.diff %}
                {% if operation.op == 'add' %}
                   <span class="version-op-add">{% trans "Added:" %} {{ operation.path }} => {{ operation.value|prettyjson }}</span>
                {% elif operation.op == 'remove' %}
                   <span class="version-op-remove">{% trans "Removed:" %} {{ operation.path }}
                    {% blocktrans trimmed with previous=operation.previous_value|prettyjson %}
                    (previously it was {{ previous }}){% endblocktrans %}</span>
                {% elif operation.op == 'replace' %}
                   <span class="version-op-replace">{% blocktrans trimmed with field=operation.path previous=operation.previous_value|prettyjson current=operation.value|prettyjson %}
                   At {{ field }} replaced {{ previous }} with {{ current }}</span>
                   {% endblocktrans %}
                {% else %}
                   <span class="version-op-unknown">{% trans "UNEXPECTED OPERATION:" %} {{ operation|prettyjson }}</span>
                {% endif %}<br/>
              {% endfor %}
            </p>
          </dd>
          {% if user.is_authenticated and not forloop.first %}
          <dt>{% trans "Revert to this" %}</dt>
          <dd>
            <form id="revert-form-{{ version.version_id }}" action="{% url 'person-revert' person_id=person.id %}" method="post" class="version-revert">
              {% csrf_token %}
              <input type="hidden" name="version_id" value="{{ version.version_id }}"/>
              <input type="text" name="source" id="id_source" maxlength="512" required="required" value="{% blocktrans with id=version.version_id %}Reverting to version {{ id }} because…{% endblocktrans %}"/>
              <input type="submit" class="button tiny alert" value="{% trans "Revert" %}" />
            </form>
          </dd>
          {% endif %}
        </dl>
      </div>
    {% endfor %}
</div>

candidates/templates/candidates/record-winner.html
{% extends 'base.html' %}
{% load i18n %}

{% block body_class %}{% endblock %}

{% block title %}{% blocktrans with name=person.name %}Confirm that {{ name }} won in {{ constituency_name }}{% endblocktrans %}{% endblock %}

{% block hero %}
  <h1>{% blocktrans with name=person.name %}Confirm that {{ name }} won{% endblocktrans %}</h1>
{% endblock %}

{% block content %}

<form method="post" action="{% url 'record-winner' election=election post_id=post_id %}">

{% csrf_token %}

{{ form.non_field_errors }}

{{ form.person_id }}

<div>
{{ form.source.errors }}
{{ form.source.label_tag }}
{{ form.source }}
</div>

<input
    type="submit"
    class="button"
    value="{% blocktrans trimmed with name=person.name party=person.last_party.name %}
Yes, {{ name }} ({{ party }}) won in {{ constituency_name }}{% endblocktrans %}"/>

<p>
<a href="{% url 'constituency' election=election post_id=post_id ignored_slug=constituency_name|slugify %}" class="button">{% trans "Cancel" %}</a>
</p>

</form>

{% endblock %}