candidates/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

import candidates.views as views

from .feeds import RecentChangesFeed

urlpatterns = \
    patterns('',
        (r'^', include(settings.ELECTION_APP_FULLY_QUALIFIED + '.urls')),
    )

patterns_to_format = [
    {
        'pattern': r'^$',
        'view': views.AddressFinderView.as_view(),
        'name': 'lookup-address',
    },
    {
        'pattern': r'^posts$',
        'view': views.PostListView.as_view(),
        'name': 'posts',
    },
    {
        'pattern': r'^election/{election}/constituencies$',
        'view': views.ConstituencyListView.as_view(),
        'name': 'constituencies'
    },
    {
        'pattern': r'^election/{election}/constituencies/unlocked$',
        'view': views.ConstituenciesUnlockedListView.as_view(),
        'name': 'constituencies-unlocked'
    },
    {
        'pattern': r'^election/{election}/constituencies/declared$',
        'view': views.ConstituenciesDeclaredListView.as_view(),
        'name': 'constituencies-declared'
    },
    {
        'pattern': r'^election/{election}/post/{post}/record-winner$',
        'view': views.ConstituencyRecordWinnerView.as_view(),
        'name': 'record-winner'
    },
    {
        'pattern': r'^election/{election}/post/{post}/retract-winner$',
        'view': views.ConstituencyRetractWinnerView.as_view(),
        'name': 'retract-winner'
    },
    {
        'pattern': r'^election/{election}/post/invalidate$',
        'view': views.InvalidatePostView.as_view(),
        'name': 'post-cache-invalidate'
    },
    {
        'pattern': r'^election/{election}/post/{post}/(?P<ignored_slug>.*).csv$',
        'view': views.ConstituencyDetailCSVView.as_view(),
        'name': 'constituency_csv'
    },
    {
        'pattern': r'^election/{election}/post/{post}/(?P<ignored_slug>.*)$',
        'view': views.ConstituencyDetailView.as_view(),
        'name': 'constituency'
    },
    {
        'pattern': r'^election/{election}/post/lock$',
        'view': views.ConstituencyLockView.as_view(),
        'name': 'constituency-lock'
    },
    {
        'pattern': r'^election/{election}/candidacy$',
        'view': views.CandidacyView.as_view(),
        'name': 'candidacy-create'
    },
    {
        'pattern': r'^election/{election}/candidacy/delete$',
        'view': views.CandidacyDeleteView.as_view(),
        'name': 'candidacy-delete'
    },
    {
        'pattern': r'^election/{election}/person/create/$',
        'view': views.NewPersonView.as_view(),
        'name': 'person-create'
    },
    {
        'pattern': r'^person/(?P<person_id>\d+)/update$',
        'view': views.UpdatePersonView.as_view(),
        'name': 'person-update'
    },
    {
        'pattern': r'^update-disallowed$',
        'view': TemplateView.as_view(template_name="candidates/update-disallowed.html"),
        'name': 'update-disallowed'
    },
    {
        'pattern': r'^all-edits-disallowed$',
        'view': TemplateView.as_view(template_name="candidates/all-edits-disallowed.html"),
        'name': 'all-edits-disallowed'
    },
    {
        'pattern': r'^person/(?P<person_id>\d+)/revert$',
        'view': views.RevertPersonView.as_view(),
        'name': 'person-revert'
    },
    {
        'pattern': r'^person/(?P<person_id>\d+)/merge$',
        'view': views.MergePeopleView.as_view(),
        'name': 'person-merge'
    },
    {
        'pattern': r'^person/(?P<person_id>\d+)(?:/(?P<ignored_slug>.*))?$',
        'view': views.PersonView.as_view(),
        'name': 'person-view'
    },
    {
        'pattern': r'^areas/(?P<type_and_area_ids>.*?)(?:/(?P<ignored_slug>.*))?$',
        'view': views.AreasView.as_view(),
        'name': 'areas-view',
    },
    {
        'pattern': r'^areas-of-type/(?P<mapit_type>.*?)(?:/(?P<ignored_slug>.*))?$',
        'view': views.AreasOfTypeView.as_view(),
        'name': 'areas-of-type-view',
    },
    {
        'pattern': r'^election/{election}/party/(?P<organization_id>[a-z-]+(:[-\d]+)?)/(?P<ignored_slug>.*)$',
        'view': views.PartyDetailView.as_view(),
        'name': 'party'
    },
    {
        'pattern': r'^election/{election}/parties/?$',
        'view': views.PartyListView.as_view(),
        'name': 'party-list'
    },
    {
        'pattern': r'^recent-changes$',
        'view': views.RecentChangesView.as_view(),
        'name': 'recent-changes'
    },
    {
        'pattern': r'^leaderboard$',
        'view': views.LeaderboardView.as_view(),
        'name': 'leaderboard'
    },
    {
        'pattern': r'^leaderboard/contributions.csv',
        'view': views.UserContributions.as_view(),
        'name': 'user-contributions'
    },
    {
        'pattern': r'^feeds/changes.xml',
        'view': RecentChangesFeed(),
        'name': 'changes_feed'
    },
    {
        'pattern': r'^help/api',
        'view': views.HelpApiView.as_view(),
        'name': 'help-api'
    },
    {
        'pattern': r'^help/about',
        'view': views.HelpAboutView.as_view(),
        'name': 'help-about'
    },
    {
        'pattern': r'^help/privacy',
        'view': TemplateView.as_view(template_name="candidates/privacy.html"),
        'name': 'help-privacy'
    },
    {
        'pattern': r'^copyright-question',
        'view': views.AskForCopyrightAssigment.as_view(),
        'name': 'ask-for-copyright-assignment'
    },
    {
        'pattern': r'^person/invalidate$',
        'view': views.InvalidatePersonView.as_view(),
        'name': 'person-cache-invalidate'
    },
]

urlpatterns += [
    url(
        p['pattern'].format(
            election=settings.ELECTION_RE,
            post=r'(?P<post_id>[-\w]+)',
        ),
        p['view'],
        name=p['name'],
    )
    for p in patterns_to_format
]

urlpatterns += [
    url(r'^numbers/', include('cached_counts.urls')),
    url(r'^moderation/', include('moderation_queue.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

elections/ar_elections_2015/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        r'^$',
        views.ArgentineAddressFinder.as_view(),
        name='lookup-address',
    ),
    url(
        r'^help/reutiliza$',
        TemplateView.as_view(template_name='candidates/reuse.html'),
        name='help-reuse',
    ),
]

mysite/urls.py
import sys

from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    url(r'^', include('candidates.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^upload_document/', include('official_documents.urls')),
    url(r'^results/', include('results.urls')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

if settings.DEBUG or ('test' in sys.argv):
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.conf.urls import patterns, url

from .views import IncompleteFieldView, TaskHomeView

urlpatterns = patterns('',
    url(r'^$', TaskHomeView.as_view(), name='tasks_home'),
    url(
        r'(?P<field>[a-z_\-\.]+)/',
        IncompleteFieldView.as_view(),
        name='incomplete_view',
    ),
)

elections/uk_general_election_2015/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.core.exceptions import ValidationError

from candidates.election_specific import MAPIT_DATA

from candidates.mapit import BaseMapItException
from .mapit import get_wmc_from_postcode

class PostcodeForm(forms.Form):
    postcode = forms.CharField(
        label='Enter your postcode',
        max_length=20
    )

    def clean_postcode(self):
        postcode = self.cleaned_data['postcode']
        try:
            # Go to MapIt to check if this postcode is valid and
            # contained in a constituency. (If it's valid then the
            # result is cached, so this doesn't cause a double lookup.)
            get_wmc_from_postcode(postcode)
        except BaseMapItException as e:
            raise ValidationError(unicode(e))
        return postcode

class ConstituencyForm(forms.Form):
    constituency = forms.ChoiceField(
        label='Select a constituency',
        choices=[('none', '')] + sorted(
            [
                (mapit_id, constituency['name'])
                for mapit_id, constituency
                in MAPIT_DATA.areas_by_id[('WMC', 22)].items()
            ],
            key=lambda t: t[1]
        )
    )

    def clean_constituency(self):
        constituency = self.cleaned_data['constituency']
        if constituency == 'none':
            raise ValidationError("You must select a constituency")
        return constituency

candidates/views/agreement.py
from django.views.generic import FormView
from django.http import HttpResponseRedirect
from django.utils.http import urlquote
from urlparse import urlparse

from ..forms import UserTermsAgreementForm

class AskForCopyrightAssigment(FormView):

    form_class = UserTermsAgreementForm
    template_name = 'candidates/ask-for-copyright-assignment.html'

    def get_initial(self):
        initial = super(AskForCopyrightAssigment, self).get_initial().copy()
        next_url = self.request.GET['next']
        parsed_url = urlparse(next_url)
        initial['next_path'] = parsed_url.path
        return initial

    def form_valid(self, form):
        ta = self.request.user.terms_agreement
        ta.assigned_to_dc = True
        ta.save()
        return HttpResponseRedirect(form.cleaned_data['next_path'])

    def get_context_data(self, **kwargs):
        context = super(AskForCopyrightAssigment, self) \
            .get_context_data(**kwargs)
        context['next_path_escaped'] = urlquote(self.request.GET['next'])
        return context

candidates/views/areas.py
# -*- coding: utf-8 -*-

import re

from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseBadRequest
from django.views.generic import TemplateView
from django.utils.text import slugify
from django.utils.translation import ugettext as _

from candidates.cache import get_post_cached, UnknownPostException
from candidates.models.auth import get_edits_allowed
from candidates.popit import PopItApiMixin

from ..election_specific import AREA_POST_DATA, MAPIT_DATA
from ..forms import NewPersonForm
from .helpers import get_people_from_memberships

class AreasView(PopItApiMixin, TemplateView):
    template_name = 'candidates/areas.html'

    def get(self, request, *args, **kwargs):
        self.types_and_areas = []
        for type_and_area in kwargs['type_and_area_ids'].split(','):
            m = re.search(r'^([A-Z0-9]{3})-(\d+)$', type_and_area)
            if not m:
                message = _("Malformed type and area: '{0}'")
                return HttpResponseBadRequest(message.format(type_and_area))
            self.types_and_areas.append(m.groups())
        try:
            view = super(AreasView, self).get(request, *args, **kwargs)
        except UnknownPostException:
            message = _("Malformed type and area: '{0}'")
            return HttpResponseBadRequest(message.format(kwargs['type_and_area_ids']))
        return view

    def get_context_data(self, **kwargs):
        context = super(AreasView, self).get_context_data(**kwargs)
        all_area_names = set()
        context['posts'] = []
        for mapit_type, area_id in self.types_and_areas:
            # Show candidates from the current elections:
            for election, election_data in settings.ELECTIONS_CURRENT:
                mapit_generation = election_data['mapit_generation']
                if mapit_type in election_data['mapit_types']:
                    mapit_tuple = (mapit_type, mapit_generation)
                    post_id = AREA_POST_DATA.get_post_id(election, mapit_type, area_id)
                    post_data = get_post_cached(self.api, post_id)['result']
                    area_name = MAPIT_DATA.areas_by_id[mapit_tuple][area_id]['name']
                    all_area_names.add(area_name)
                    locked = post_data.get('candidates_locked', False)
                    current_candidates, _ = get_people_from_memberships(
                        election_data,
                        post_data['memberships'],
                    )
                    context['posts'].append({
                        'election': election,
                        'election_data': election_data,
                        'post_data': post_data,
                        'candidates_locked': locked,
                        'candidate_list_edits_allowed':
                        get_edits_allowed(self.request.user, locked),
                        'candidates': current_candidates,
                        'add_candidate_form': NewPersonForm(
                            election=election,
                            initial={
                                ('constituency_' + election): post_id,
                                ('standing_' + election): 'standing',
                            },
                            hidden_post_widget=True,
                        ),
                    })
        context['all_area_names'] = u' — '.join(all_area_names)
        context['suppress_official_documents'] = True
        return context

class AreasOfTypeView(PopItApiMixin, TemplateView):
    template_name = 'candidates/areas-of-type.html'

    def get_context_data(self, **kwargs):
        context = super(AreasOfTypeView, self).get_context_data(**kwargs)
        requested_mapit_type = kwargs['mapit_type']
        all_mapit_tuples = set(
            (mapit_type, election_data['mapit_generation'])
            for election, election_data in settings.ELECTIONS_CURRENT
            for mapit_type in election_data['mapit_types']
            if mapit_type == requested_mapit_type
        )
        if not all_mapit_tuples:
            raise Http404(_("Area '{0}' not found").format(requested_mapit_type))
        if len(all_mapit_tuples) > 1:
            message = _("Multiple MapIt generations for type {mapit_type} found")
            raise Exception(message.format(mapit_type=requested_mapit_type))
        mapit_tuple = list(all_mapit_tuples)[0]
        areas = [
            (
                reverse(
                    'areas-view',
                    kwargs={
                        'type_and_area_ids': '{type}-{area_id}'.format(
                            type=requested_mapit_type,
                            area_id=area['id']
                        ),
                        'ignored_slug': slugify(area['name'])
                    }
                ),
                area['name'],
                area['type_name'],
            )
            for area in MAPIT_DATA.areas_by_id[mapit_tuple].values()
        ]
        areas.sort(key=lambda a: a[1])
        context['areas'] = areas
        context['area_type_name'] = _('[No areas found]')
        if areas:
            context['area_type_name'] = areas[0][2]
        return context

candidates/views/cache.py
import re

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import View

from braces.views import LoginRequiredMixin, StaffuserRequiredMixin

from candidates.cache import invalidate_person, invalidate_posts
from elections.mixins import ElectionMixin

# class InvalidatePersonView(LoginRequiredMixin, StaffuserRequiredMixin, View):
class InvalidatePersonView(View):

    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        person_id = request.POST['person_id']
        if re.search(r'^\d+$', person_id):
            invalidate_person(person_id)
        return HttpResponseRedirect(
            reverse('person-view', kwargs={
                'person_id': person_id
            })
        )


class InvalidatePostView(ElectionMixin, LoginRequiredMixin, StaffuserRequiredMixin, View):

    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        post_id = request.POST['post_id']
        if re.search(r'^\d+$', post_id):
            invalidate_posts([post_id])
        return HttpResponseRedirect(
            reverse('constituency', kwargs={
                'post_id': post_id,
                'ignored_slug': '',
                'election': self.election,
            })
        )

candidates/views/posts.py
from django.conf import settings
from django.views.generic import TemplateView

from ..cache import get_all_posts_cached
from ..popit import PopItApiMixin

class PostListView(PopItApiMixin, TemplateView):
    template_name = 'candidates/posts.html'

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        all_posts = {}
        for election, election_data in settings.ELECTIONS_CURRENT:
            role = election_data['for_post_role']
            all_posts[election] = {
                'posts': get_all_posts_cached(self.api, role),
                'election_data': election_data,
            }
        context['all_posts'] = all_posts
        return context

elections/uk_general_election_2015/templates/candidates/finder.html
{% extends 'base.html' %}
{% load i18n %}
{% load metadescription %}

{% block extra_head %}
    <!-- Open Graph data -->
    <meta property="og:title" content="{% trans "YourNextMP" %}" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:image" content="{{ 'img/logo.png'|static_image_path:request }}" />
    <meta property="og:image:height" content="80" />
    <meta property="og:image:width" content="80" />
    <meta property="og:site_name" content="{% trans "YourNextMP" %}" />
    <meta property="og:description" content="{% blocktrans with election_name=election_data.name %}YourNextMP - {{ election_name }} candidates{% endblocktrans %}">
    <meta property="og:locale" content="{{ LOCALE }}" />

    <!-- Twitter card data -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="{% trans "@yournextmp" %}" />
    <meta name="twitter:title" content="{% trans "YourNextMP" %}" />
    <meta property="twitter:image" content="{{ 'img/logo.png'|static_image_path:request }}" />
    <meta property="twitter:image:height" content="120" />
    <meta property="twitter:image:width" content="120" />
    <meta name="twitter:url" content="{{ request.build_absolute_uri }}" />
    <meta name="twitter:description" content="{% blocktrans with election_name=election_data.name %}YourNextMP - {{ election_name }} candidates{% endblocktrans %}" />
{% endblock %}

{% block body_class %}finder{% endblock %}

{% block extra_js %}
  <script>
    $(function() {
      /* Turn the constituency <select> into a nice Select2 box */
      $('#id_constituency').select2({
        placeholder: 'Constituency',
        allowClear: true,
        width: '100%'
      });
      /* Swap between the postcode and name select form when clicking on the
         .show-other-form button */
      $('.show-other-form').on('click', function(e){
        $(this).parents('form').hide().siblings('form').show();
        e.preventDefault();
      })
    });
  </script>
{% endblock %}

{% block hero %}

  <h1><em>The</em> high quality source of free candidate data for the 2015 General Election</h1>

  <p class="lead"> Don’t pay for a candidate database sold by a data vendor —
it’s a waste of money.</p>

{% endblock %}

{% block content %}

<div class="finder__forms">

  <form id="form-postcode" action="{% url 'lookup-postcode' %}" method="post" {% if show_name_form %}style="display: none"{% endif %}>
    {{ postcode_form.as_p }}
    <input type="submit" class="button" value="Show candidates" />
    <a class="show-other-form" href="{% url 'lookup-name' %}">Or select a constituency</a>
  </form>

  <form id="form-name" action="{% url 'lookup-name' %}" method="post" {% if show_postcode_form %}style="display: none"{% endif %}>
    {{ constituency_form.as_p }}
    <input type="submit" class="button" value="Show candidates" />
    <a class="show-other-form" href="{% url 'lookup-postcode' %}">Or search by postcode</a>
  </form>

</div>

</div><!-- close .container so we can go full width with .finder__description -->

<div class="finder__description">
  <div class="container">
    <p>At the last election, YourNextMP’s volunteer-sourced database of
      candidates was found to be at least as accurate as one of the most
      popular commercial datasets.
    </p>
    <p>YourNextMP is the most comprehensive transparently sourced and
      well-structured database of General Election 2015 candidate data.
      <a href="{% url 'help-api' %}">Get the data now</a>, or
      <a href="{% url "tasks_home" %}">help by contributing new candidate
      details.</a>
    </p>
  </div>
</div>

<div class="container"><!-- reopen new .container -->

<div class="finder__activity">
  <div class="finder__activity__changes">
    <h2><a href="{% url 'recent-changes' %}">Recent changes</a></h2>
    <ol>
      {% for action in recent_actions %}
        <li>User <strong>{{ action.user.username }}</strong>
          {% if action.action_type == 'person-create' %}
            {% if action.popit_person_id %}
              created <a href="{% url 'person-view' person_id=action.popit_person_id %}">a new candidate</a>
            {% else %}
              is creating a new candidate
            {% endif %}
          {% elif action.action_type == 'person-merge' %}
            merged another candidate into <a href="{% url 'person-view' person_id=action.popit_person_id %}">candidate #{{ action.popit_person_id }}</a>
          {% elif action.action_type == 'photo-upload' %}
            uploaded a photo of <a href="{% url 'person-view' person_id=action.popit_person_id %}">candidate #{{ action.popit_person_id }}</a> for moderation
          {% elif action.action_type == 'photo-approve' %}
            approved an uploaded photo of <a href="{% url 'person-view' person_id=action.popit_person_id %}">candidate #{{ action.popit_person_id }}</a>
          {% elif action.action_type == 'photo-reject' %}
            rejected an uploaded photo of <a href="{% url 'person-view' person_id=action.popit_person_id %}">candidate #{{ action.popit_person_id }}</a>
          {% elif action.action_type == 'person-revert' %}
            reverted to an earlier version of <a href="{% url 'person-view' person_id=action.popit_person_id %}">candidate #{{ action.popit_person_id }}</a>
          {% elif action.action_type == 'candidacy-create' %}
            confirmed candidacy for <a href="{% url 'person-view' person_id=action.popit_person_id %}">candidate #{{ action.popit_person_id }}</a>
          {% elif action.action_type == 'candidacy-delete' %}
            removed candidacy for <a href="{% url 'person-view' person_id=action.popit_person_id %}">candidate #{{ action.popit_person_id }}</a>
          {% elif action.action_type == 'constituency-lock' %}
            locked a constituency
          {% elif action.action_type == 'constituency-unlock' %}
            unlocked a constituency
          {% elif action.action_type == 'set-candidate-elected' %}
            marked <a href="{% url 'person-view' person_id=action.popit_person_id %}">candidate #{{ action.popit_person_id }}</a> as the winner
          {% else %}
            updated <a href="{% url 'person-view' person_id=action.popit_person_id %}">candidate #{{ action.popit_person_id }}</a>
          {% endif %}
        <span class="when">{{ action.created|timesince }} ago</span></li>
      {% endfor %}
    </ol>
    <p class="more"><a href="{% url 'recent-changes' %}">Show more changes…</a></p>
  </div>
  <div class="finder__activity__leaderboard">
    <h2><a href="{% url 'leaderboard' %}">Top users this week</a></h2>
    <ol>
      {% for row in top_users %}
        <li><strong>{{ row.username }}</strong> <span class="edits">{{ row.edit_count }} edit{{ row.edit_count|pluralize }}</span></li>
      {% endfor %}
    </ol>
    <p class="more"><a href="{% url 'leaderboard' %}">Show full leaderboard…</a></p>
  </div>
</div>

{% endblock %}